version: "2"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    image: nb2kg/notebook
    container_name: nb2kg-notebook
    ports:
     - "9888:8888"
    environment:
      KG_URL: http://nb2kg-kg:8888
      KG_AUTH_TOKEN: colonels
    command: >
      jupyter notebook
      --NotebookApp.ip=0.0.0.0
      --NotebookApp.session_manager_class=nb2kg.managers.SessionManager
      --NotebookApp.kernel_manager_class=nb2kg.managers.RemoteKernelManager
      --NotebookApp.kernel_spec_manager_class=nb2kg.managers.RemoteKernelSpecManager

  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kg
    image: nb2kg/kernel_gateway
    container_name: nb2kg-kg
    ports:
     - "9889:8888"
    environment:
      KG_ALLOW_ORIGIN: '*'
      KG_LIST_KERNELS: "True"
      KG_AUTH_TOKEN: colonels
    command: >
      jupyter kernelgateway
      --KernelGatewayApp.ip=0.0.0.0
      --KernelGatewayApp.log_level=DEBUG
